### ISSUE TITLE
Use FM-index & json for DBCS decoding.

### ISSUE THREAD

**Issue by lygstate** [lifthrasiir/rust-encoding#95]

**Comment by lifthrasiir** [comment]
Before starting the reply...

I wouldn't blindly reject the issue without detailed descriptions, but this and previous issue (#94) greatly lacks the information and strongly suggests that you haven't read the source code or documentation at all. Sometimes it may be the best thing you can do, but still you need to clearly show *what do you mean* and *what do you know about that right now*. Neither is present in your issues; please make sure of them.

The data tables of Encoding are ultimately a set of lookup tables describing a function from integers to integers ([WHATWG Encoding Standard](http://encoding.spec.whatwg.org/) standardizes on that format, and I don't see any reason that other types of data are better suited). They are currently implemented in the two levels of [trie](https://en.wikipedia.org/wiki/Trie): the upper bits are used to get the offset to the lower table, and that offset and the lower bits are used to get the actual value.

The [FM-index](https://en.wikipedia.org/wiki/FM-index) is a data structure similar to the suffix tree but constructed via the [BWT](https://en.wikipedia.org/wiki/Burrows%E2%80%93Wheeler_transform). If my understanding is correct, the BWT is defined as the last column of lexicographically sorted list of all possible rotations of the input string (plus EOF); it is noted that the first column of that list is similar to the suffix tree so having some way to convert the last column to the first column would give a single data structure allowing bidirectional mapping.

It is unclear to me that either FM-index or JSON would benefit encoding them. While FM-index is an interesting data structure (and I think I understood why this issue brings it to the table) the size of the raw index is about the input length times the number of distinct symbols; the distinct symbols, in this case, would almost equal to the input length, so the space complexity is O(n^2). Of course it can be "solved" by compressing it (and the whole point of FM-index is of course that the raw tables have rather lower information entropy like BWT) but I guess it would be quite complex and I cannot easily justify the complexity. Also we now have an option to significantly reduce the table at the expense of the encoding performance, so I naturally want that the replacement is either faster (probably very hard when you are replacing tries) or space efficient than those two approaches. And I don't understand that JSON is ever relevant to the character encodings at all.

**Comment by lygstate** [comment]
@lifthrasiir  Thanks for your detail explain, I am still trying to figure out if that's possible to apply FM-index to character encoding-decoding, (If that have both space efficient & performance gain). I trying to do it based on pure javascript. So the work still not complete yet.
The JSON have nothing to do with encoding. I am just trying to use JSON to storage some meta data for encoding/decoding about the FM-index.
Cause at last, the FM-index compressed encoding/decoding may merely a Sequence that have no meta data. (Cause the encoding sequence may have may holes, and we would not encoding/decoding those holes), so we need some description meta data to description those wholes and do not decode/encode those things.

**Comment by lygstate** [comment]
@lifthrasiir I was wrong about FM-index, it's not suite for this usage condition.
