### ISSUE TITLE
Need the performance data for rust-encoding.

### ISSUE THREAD

**Issue by lygstate** [lifthrasiir/rust-encoding#96]
The performance data for iconv-lite is:
https://github.com/ashtuchkin/iconv-lite#encodingdecoding-speed

I am curious about how fast the rust-encoding is

**Comment by lifthrasiir** [comment]
It is in the order of 100 MB/s for most operations I have tested. (I have used `cargo bench` in my MacBook Air.) The exact figure would depend on the environment and I have no interest in comparing with iconv-lite.
