### ISSUE TITLE
Issue with multi-codepoint graphemes

### ISSUE THREAD

**Issue by sellibitze** [lifthrasiir/rust-encoding#98]
I just tried encoding `"A\u{308}"`, which is another Unicode representation of `"Ä"` to ISO8859-1 with `EncoderTrap::Replace` but instead of `"Ä"` I get `"A?"`. Is this intentional or an oversight?

**Comment by SimonSapin** [comment]
What you call “another Unicode representation”, [UAX # 15](http://unicode.org/reports/tr15/#Canon_Compat_Equivalence) calls “canonically equivalent”. This library is not aware of this sort of equivalence. It only encodes and decodes one code point at a time.

You may want to use the [unicode-normalization](https://github.com/unicode-rs/unicode-normalization) crate to normalize before encoding. For example, *Normalization Form C* will replace `A\u{308}` with `\u{c4}`.

**Comment by lifthrasiir** [comment]
Yes, it is intentional and out of scope of this library as @SimonSapin said. Closing.
